#!/usr/bin/env python3
"""
Build script for RAW Image Viewer Windows/macOS executable
Handles dependency installation and executable creation.
"""

VERSION = "3.1.0"

import os
import subprocess
import platform
import shutil
import time
import sys
import argparse
from pathlib import Path

# Repository root (directory containing this script)
REPO_ROOT = Path(__file__).resolve().parent
_BUILD_T0 = time.time()


def _build_elapsed() -> float:
    return time.time() - _BUILD_T0


def _build_log(step: str) -> None:
    print(f"[BUILD][{_build_elapsed():.1f}s] {step}")


def _env_flag(name: str) -> bool:
    return os.environ.get(name, "").strip().lower() in ("1", "true", "yes", "on")


def _using_pixi_build_env() -> bool:
    """True when build.py runs inside the repo's pixi default env."""
    try:
        exe = Path(sys.executable).resolve()
        pixi_env = (REPO_ROOT / ".pixi" / "envs" / "default").resolve()
        return str(exe).startswith(str(pixi_env))
    except OSError:
        return False


def _build_skip_deps() -> bool:
    if _env_flag("RAWVIEWER_BUILD_SKIP_DEPS"):
        return True
    # build_macos.sh uses pixi with a locked env; pip --upgrade every run is wasted time.
    if _using_pixi_build_env() and _env_flag("RAWVIEWER_USE_SYSTEM_PYTHON_BUILD"):
        return True
    return False


def _build_incremental() -> bool:
    return _env_flag("RAWVIEWER_BUILD_INCREMENTAL")

_WINDOWS_LITE_PIXI_SKIP = (
    "huggingface_hub",
    "onnxruntime-gpu",
    "onnxruntime-directml",
    "requests",
    # GPU demosaic / optional AI denoise backend. CUDA torch wheels dominate
    # Windows install size; Lite keeps CPU Fast RAW (cv2) + Adjust editing.
    "torch",
    "torchvision",
    "kornia",
    # CuPy GPU demosaic is CUDA-edition-only; Standard keeps CPU Fast RAW.
    "cupy-cuda12x",
)
# opencv-python-headless was in this skip list -- correct while cv2 was only
# used by the (Lite-excluded) semantic search preprocessing, but the
# scene-linear Adjust panel added since (raw_edit_pipeline.py,
# raw_chroma_denoise.py, raw_detail_enhance.py, raw_hsl.py,
# raw_lens_correction.py) imports cv2 unconditionally -- stripping it from
# the Lite pixi manifest would make every Adjust panel control crash with
# ModuleNotFoundError on first use. See docs/EDIT_PIPELINE.md "Installer size".
# torch/kornia stay skipped: Lite is browse + light Adjust on CPU; Full ships
# CUDA demosaic separately.


def write_app_version() -> None:
    """Write src/app_version.py for runtime imports (single source: VERSION above)."""
    path = REPO_ROOT / "src" / "app_version.py"
    content = (
        '"""Generated by build.py — do not edit; change VERSION in build.py and re-sync."""\n\n'
        f'APP_VERSION = "{VERSION}"\n'
    )
    # Skip identical rewrites: an mtime bump invalidates PyInstaller's PYZ cache
    # and cascades into a full COLLECT/BUNDLE recopy on incremental builds.
    if not (path.is_file() and path.read_text(encoding="utf-8") == content):
        path.write_text(content, encoding="utf-8")
    print(f"[INFO] App version: {VERSION} -> {path}")


def sync_pixi_toml_version() -> None:
    """Keep pixi.toml workspace version aligned with build.py VERSION."""
    import re

    path = REPO_ROOT / "pixi.toml"
    text = path.read_text(encoding="utf-8")
    new_text, count = re.subn(
        r'^version = ".*"$',
        f'version = "{VERSION}"',
        text,
        count=1,
        flags=re.MULTILINE,
    )
    if count != 1:
        raise RuntimeError(f"Could not update version in {path}")
    if new_text != text:
        path.write_text(new_text, encoding="utf-8")
        print(f"[INFO] pixi.toml version -> {VERSION}")


def sync_version_artifacts() -> None:
    """Propagate VERSION to generated/runtime version files."""
    write_app_version()
    sync_pixi_toml_version()


def write_build_profile(profile: str) -> None:
    profile = profile.strip().lower()
    if profile in ("standard", "std"):
        profile = "lite"
    elif profile in ("plus",):
        profile = "full"
    if profile not in ("full", "lite"):
        raise ValueError(f"Unknown build profile: {profile}")
    path = REPO_ROOT / "src" / "build_profile.py"
    content = (
        '"""Baked at build time by build.py (--profile full|plus|lite|standard).\n'
        "Internal ids: lite = Standard edition, full = Plus edition.\n"
        '"""\n\n'
        f'PROFILE = "{profile}"\n'
    )
    # Skip identical rewrites (mtime bump would invalidate PyInstaller's cache).
    if not (path.is_file() and path.read_text(encoding="utf-8") == content):
        path.write_text(content, encoding="utf-8")
    edition = "Standard" if profile == "lite" else "Plus"
    print(f"[INFO] Build profile: {profile} ({edition}) -> {path}")


def _project_venv_python() -> Path:
    if platform.system() == "Windows":
        return REPO_ROOT / "rawviewer_env" / "Scripts" / "python.exe"
    return REPO_ROOT / "rawviewer_env" / "bin" / "python3"


def _running_inside_project_venv() -> bool:
    try:
        return Path(sys.executable).resolve() == _project_venv_python().resolve()
    except OSError:
        return False


def _is_externally_managed_python() -> bool:
    """True for Homebrew / Debian PEP 668 installs where ``pip install`` to system is blocked."""
    return (Path(sys.prefix) / "EXTERNALLY-MANAGED").is_file()


def _should_use_project_venv_for_build() -> bool:
    """
    Prefer ./rawviewer_env so ``pip install`` / PyInstaller do not hit system Python limits.

    - macOS: always (matches ``scripts/Launch/macos/build_macos.sh``; Homebrew 3.14 may block pip without an
      ``EXTERNALLY-MANAGED`` file under ``sys.prefix``).
    - Linux: when PEP 668 marker is present.
    Set ``RAWVIEWER_USE_SYSTEM_PYTHON_BUILD=1`` to skip and use the current interpreter.
    """
    if os.environ.get("RAWVIEWER_USE_SYSTEM_PYTHON_BUILD", "").strip().lower() in (
        "1",
        "true",
        "yes",
    ):
        return False
    if _running_inside_project_venv():
        return False
    if platform.system() == "Darwin":
        return True
    if _is_externally_managed_python():
        return True
    return False


def ensure_project_venv_and_reexec() -> None:
    """
    Create ./rawviewer_env if needed and re-exec this script with that interpreter.

    Skips when already using ./rawviewer_env (e.g. ``scripts/Launch/macos/build_macos.sh``) or when
    ``RAWVIEWER_USE_SYSTEM_PYTHON_BUILD=1``.
    """
    if not _should_use_project_venv_for_build():
        return
    vpy = _project_venv_python()
    venv_dir = REPO_ROOT / "rawviewer_env"
    if not vpy.is_file():
        if platform.system() == "Darwin":
            venv_msg = (
                "[INFO] Creating ./rawviewer_env — macOS builds default to an isolated venv "
                "(reliable pip/PyInstaller vs Homebrew Python). "
                "Set RAWVIEWER_USE_SYSTEM_PYTHON_BUILD=1 to opt out."
            )
        else:
            venv_msg = (
                "[INFO] Creating ./rawviewer_env — system Python is PEP 668 externally managed; "
                "pip cannot install into it."
            )
        print(venv_msg)
        rc = subprocess.run(
            [sys.executable, "-m", "venv", str(venv_dir)],
            check=False,
        ).returncode
        if rc != 0 or not vpy.is_file():
            print(
                "[ERROR] Could not create ./rawviewer_env. From the repo root try:\n"
                "  ./scripts/Launch/macos/build_macos.sh\n"
                "or:  python3 -m venv rawviewer_env && ./rawviewer_env/bin/python3 -m pip install -U pip && "
                "./rawviewer_env/bin/python3 build.py"
            )
            sys.exit(1)
    script = Path(__file__).resolve()
    argv = [str(vpy), str(script), *sys.argv[1:]]
    print(f"[INFO] Re-running build with project venv: {vpy}")
    os.execv(str(vpy), argv)


def run_command(cmd):
    # Support both string commands and lists
    if isinstance(cmd, list):
        result = subprocess.run(cmd)
    else:
        result = subprocess.run(cmd, shell=True)
    return result.returncode == 0


def _macos_app_bundle_name(profile: str = "full") -> str:
    # Filesystem names kept stable for upgrades; display names are Standard/Plus.
    if profile.strip().lower() in ("lite", "standard"):
        return "RAWviewer_Lite"
    return "RAWviewer"


def update_macos_plist(app_path, profile: str = "full"):
    """Update Info.plist in macOS app bundle to add file associations"""
    plist_path = os.path.join(app_path, 'Contents', 'Info.plist')
    if not os.path.exists(plist_path):
        print(f"[WARNING] Info.plist not found at {plist_path}")
        return False
        
    try:
        import plistlib
        with open(plist_path, 'rb') as f:
            plist = plistlib.load(f)
            
        # Define supported extensions
        image_extensions = [
            'jpg', 'jpeg', 'png', 'bmp', 'gif', 'webp', 'tif', 'tiff', 'heic',
            'cr2', 'cr3', 'nef', 'arw', 'dng', 'raf', 'orf', 'rw2', 'pef', 'srw', 'crw', 'mef', 'mrw'
        ]
        
        # Add CFBundleDocumentTypes if not present
        if 'CFBundleDocumentTypes' not in plist:
            plist['CFBundleDocumentTypes'] = []
            
        # Check if our document type is already defined
        doc_type_exists = any(
            doc.get('CFBundleTypeName') == 'Image File' for doc in plist['CFBundleDocumentTypes']
        )
        
        if not doc_type_exists:
            doc_type = {
                'CFBundleTypeName': 'Image File',
                'CFBundleTypeRole': 'Viewer',
                'LSHandlerRank': 'Alternate',
                'LSItemContentTypes': [
                    'public.image',
                    'public.camera-raw-image'
                ],
                'CFBundleTypeExtensions': image_extensions
            }
            plist['CFBundleDocumentTypes'].append(doc_type)
            
        bundle_name = _macos_app_bundle_name(profile)
        is_standard = profile.strip().lower() in ("lite", "standard")
        # Bundle IDs kept stable (lite → Standard, default → Plus).
        plist['CFBundleIdentifier'] = (
            'com.markyip.rawviewer.lite' if is_standard else 'com.markyip.rawviewer'
        )
        plist['CFBundleName'] = bundle_name
        plist['CFBundleDisplayName'] = 'RAWviewer' if is_standard else 'RAWviewer Plus'
        plist['CFBundleExecutable'] = bundle_name
        plist['CFBundlePackageType'] = 'APPL'
        plist['CFBundleShortVersionString'] = VERSION
        plist['CFBundleVersion'] = VERSION
        
        # Add macOS permission usage descriptions
        # (Relevant if/when App Sandbox is enabled; current release is not sandboxed —
        #  file access follows normal POSIX permissions after the user picks a path.)
        plist['NSDesktopFolderUsageDescription'] = (
            'RAWviewer needs access to your Desktop to open and export images.'
        )
        plist['NSDocumentsFolderUsageDescription'] = (
            'RAWviewer needs access to your Documents folder to open and export images.'
        )
        plist['NSDownloadsFolderUsageDescription'] = (
            'RAWviewer needs access to your Downloads folder to open and export images.'
        )
        plist['NSRemovableVolumesUsageDescription'] = (
            'RAWviewer needs access to external volumes to open images from cameras or cards. '
            'Exporting may require a writable folder (Desktop/Pictures) if the card is read-only.'
        )
        plist['NSPhotoLibraryUsageDescription'] = (
            'RAWviewer needs access to your photo library to display images.'
        )
        plist['NSAppleEventsUsageDescription'] = (
            'RAWviewer uses AppleEvents for native file dialogs when needed.'
        )
        
        # macOS specific flags
        plist['LSMinimumSystemVersion'] = '13.0'
        plist['NSHighResolutionCapable'] = True
        plist['LSSupportsOpeningDocumentsInPlace'] = True
        plist['LSApplicationCategoryType'] = 'public.app-category.photography'

        with open(plist_path, 'wb') as f:
            plistlib.dump(plist, f)
        print("[SUCCESS] Updated Info.plist with Bundle ID, file associations and usage descriptions")
        return True
    except Exception as e:
        print(f"[ERROR] Failed to update Info.plist: {e}")
        return False


def install_dependencies(windows_accel: str = "cuda", *, profile: str = "full"):
    """Install required dependencies"""
    lite = profile.strip().lower() == "lite"
    if _build_skip_deps():
        _build_log(
            "Skipping pip install (pixi/locked env or RAWVIEWER_BUILD_SKIP_DEPS=1)"
        )
        return True

    print("Installing/upgrading dependencies...")
    system_name = platform.system()
    dependencies = [
        'PyQt6',
        'rawpy',
        'send2trash',
        'pyinstaller',
        'natsort',
        'exifread',
        'Pillow',  # Added for NEF thumbnail fallback
        'psutil',  # Added for system memory info in image_cache
        'numpy',   # Required for image processing (used in all modules)
        'qtawesome', # Required for icons in main.py
        'pycountry',  # ISO country code -> full country name
        'pillow-heif',
        # Required unconditionally by the Adjust panel (raw_edit_pipeline.py,
        # raw_chroma_denoise.py, raw_detail_enhance.py, raw_hsl.py,
        # raw_lens_correction.py / raw_tone_curve.py / raw_tone_recovery.py),
        # not just the AI/semantic-search features -- must be present in
        # every profile (lite and full) and every platform, or Adjust panel
        # controls crash on first use once packaged. See
        # docs/EDIT_PIPELINE.md "Installer size".
        'opencv-python-headless',
        'tifffile',
        'lensfunpy',
    ]

    if system_name in ("Darwin", "Windows"):
        dependencies.append("certifi")
        if not lite:
            dependencies.append("requests")
    if system_name == "Windows":
        if not lite:
            # Windows semantic backend uses ONNX with selectable acceleration backend.
            accel = (windows_accel or "cuda").strip().lower()
            if accel == "cuda":
                dependencies.append('onnxruntime-gpu')
            elif accel == "directml":
                dependencies.append('onnxruntime-directml')
            else:
                print(f"[ERROR] Unsupported Windows acceleration backend: {windows_accel}")
                return False
            dependencies.append('huggingface-hub')
    elif system_name == "Darwin":
        if not lite:
            dependencies.append('huggingface-hub')
            dependencies.append('pyobjc-framework-CoreML')
            dependencies.append('pyobjc-framework-Vision')
        dependencies.append('pyobjc-framework-Quartz')
    if system_name in ("Darwin", "Windows"):
        dependencies.append("pyexiv2")

    for dep in dependencies:
        print(f"Installing {dep}...")
        if not run_command([sys.executable, "-m", "pip", "install", "--upgrade", dep]):
            print(f"[ERROR] Failed to install {dep}")
            return False

    if system_name == "Darwin":
        print("Installing pyobjc-framework-Cocoa (macOS share sheet)...")
        if not run_command(
            [sys.executable, "-m", "pip", "install", "--upgrade", "pyobjc-framework-Cocoa"]
        ):
            print("[WARNING] pyobjc-framework-Cocoa install failed; Share may not work in the built app.")
    elif system_name == "Windows":
        print("Installing pywin32 (Windows Share verb)...")
        if not run_command([sys.executable, "-m", "pip", "install", "--upgrade", "pywin32"]):
            print("[WARNING] pywin32 install failed; Share may not work in the built app.")

    print("Dependencies installed successfully!")
    return True


def _darwin_ensure_homebrew_pyexiv2_libs() -> None:
    """
    pyexiv2's bundled libexiv2.dylib expects Homebrew libinih / gettext on the build machine
    (see https://github.com/LeoHsiao1/pyexiv2/blob/master/docs/Tutorial.md FAQ).
    """
    if platform.system() != "Darwin":
        return
    brew = shutil.which("brew")
    if not brew:
        print(
            "[INFO] Homebrew (`brew`) not on PATH. If `import pyexiv2` fails, install "
            "https://brew.sh then run: brew install inih gettext"
        )
        return
    for formula in ("inih", "gettext"):
        listed = subprocess.run(
            [brew, "list", formula],
            capture_output=True,
        )
        if listed.returncode != 0:
            print(
                f"[INFO] Installing Homebrew `{formula}` (native dependency for pyexiv2 / Exiv2)..."
            )
            subprocess.run([brew, "install", formula], check=False)


def _darwin_preflight_pyexiv2_import() -> None:
    """Fail fast with a clear message before PyInstaller touches pyexiv2."""
    if platform.system() != "Darwin":
        return
    try:
        import pyexiv2  # noqa: F401
    except Exception as e:
        print(
            "[ERROR] pyexiv2 failed to import (required for this macOS build).\n"
            "  Install native libraries, then re-run:\n"
            "    brew install inih gettext\n"
            f"  Underlying error: {e}"
        )
        sys.exit(1)


def _prepare_windows_pixi_manifest(accel: str, *, profile: str = "full") -> Path:
    """
    Create a backend-specific pixi.toml copy for Windows installer payload.
    The bundled bootstrap always copies this file as `pixi.toml`.

    Size notes (approximate installed footprint, excluding MobileCLIP ~600 MB):
      - Lite: no ORT / HF / CuPy — ~0.8–1 GB
      - Full DirectML: ORT-DirectML + models, CPU demosaic — ~1.5–2 GB
      - Full CUDA: cupy-cuda12x (+ CUDA runtime wheels) — ~1.5–2 GB (+ models)
    """
    src = REPO_ROOT / "pixi.toml"
    raw = src.read_text(encoding="utf-8")
    lite = profile.strip().lower() == "lite"
    if lite:
        kept_lines = []
        for line in raw.splitlines():
            if any(token in line for token in _WINDOWS_LITE_PIXI_SKIP):
                continue
            kept_lines.append(line)
        raw = "\n".join(kept_lines) + "\n"
        raw = raw.replace(
            "Professional RAW Image Viewer with Semantic Search",
            "Professional RAW Image Viewer (Standard — browse, cull, Adjust; no AI search)",
        )
    elif accel == "cuda":
        # CuPy demosaic + DirectML ORT for MobileCLIP (avoid a second CUDA EP stack).
        raw = raw.replace("onnxruntime-gpu", "onnxruntime-directml")
        raw = raw.replace(
            "Professional RAW Image Viewer with Semantic Search",
            "Professional RAW Image Viewer (Plus CUDA — AI search + CuPy GPU demosaic)",
        )
    elif accel == "directml":
        # Semantic search on DirectML; demosaic stays CPU Fast RAW (no CuPy).
        raw = raw.replace("onnxruntime-gpu", "onnxruntime-directml")
        directml_skip = (
            "torch",
            "torchvision",
            "kornia",
            "cupy-cuda12x",
        )
        kept_lines = []
        for line in raw.splitlines():
            if any(token in line for token in directml_skip):
                continue
            kept_lines.append(line)
        raw = "\n".join(kept_lines) + "\n"
        raw = raw.replace(
            "Professional RAW Image Viewer with Semantic Search",
            "Professional RAW Image Viewer (Plus DirectML — AI search; CPU demosaic)",
        )
    else:
        raise ValueError(f"Unsupported Windows acceleration backend: {accel}")
    tmp_dir = REPO_ROOT / "build" / "_pixi_variants"
    tmp_dir.mkdir(parents=True, exist_ok=True)
    if lite:
        suffix = "lite"
    else:
        suffix = accel
    out = tmp_dir / f"pixi-{suffix}.toml"
    out.write_text(raw, encoding="utf-8")
    return out


def _windows_setup_exe_name(accel: str, *, profile: str = "full") -> str:
    if profile.strip().lower() == "lite":
        return "RAWviewer_Setup_Lite"
    suffix = "CUDA" if accel == "cuda" else "DirectML"
    return f"RAWviewer_Setup_{suffix}"


def build_windows_launcher_stub(icon_path: str | None) -> tuple[Path, Path]:
    """Build a tiny onedir RAWviewer.exe that launches pixi in the install directory.

    onedir (not onefile) avoids PyInstaller's ``_MEI*`` extract/cleanup MessageBox
    on every short-lived launcher exit. Runtime files go in ``_launcher`` so they
    do not collide with the install folder's ``_internal/pixi``.
    """
    stub_root = REPO_ROOT / "build" / "launcher_stub"
    dist_dir = stub_root / "dist"
    work_dir = stub_root / "build"
    spec_dir = stub_root
    stub_root.mkdir(parents=True, exist_ok=True)

    for path in (dist_dir, work_dir):
        if path.exists():
            shutil.rmtree(path, ignore_errors=True)

    launcher_src = REPO_ROOT / "src" / "win_launcher.py"
    cmd = [
        sys.executable,
        "-m",
        "PyInstaller",
        "--onedir",
        "--contents-directory",
        "_launcher",
        "--windowed",
        "--noconfirm",
        "--name",
        "RAWviewer",
        "--distpath",
        str(dist_dir),
        "--workpath",
        str(work_dir),
        "--specpath",
        str(spec_dir),
        "--exclude-module",
        "PyQt6",
        "--exclude-module",
        "numpy",
        "--exclude-module",
        "PIL",
        "--exclude-module",
        "rawpy",
        "--exclude-module",
        "onnxruntime",
        str(launcher_src),
    ]
    if icon_path and os.path.isfile(icon_path):
        cmd.extend(["--icon", icon_path])

    print("[INFO] Building Windows launcher stub (RAWviewer.exe onedir)...")
    if not run_command(cmd):
        print("[ERROR] Launcher stub build failed.")
        sys.exit(1)

    out_dir = dist_dir / "RAWviewer"
    out_exe = out_dir / "RAWviewer.exe"
    out_runtime = out_dir / "_launcher"
    if not out_exe.is_file() or not out_runtime.is_dir():
        print(f"[ERROR] Launcher stub was not created under: {out_dir}")
        sys.exit(1)
    print(
        f"[INFO] Launcher stub ready: {out_exe} "
        f"({out_exe.stat().st_size:,} bytes) + {out_runtime.name}/"
    )
    return out_exe, out_runtime


def _macos_rawpy_openmp_binaries() -> list[Path]:
    """OpenMP LibRaw runtime files that must ship beside rawpy in the .app.

    Official macOS packages exclude torch, so LibRaw must use a standalone
    ``libomp.dylib`` under ``@loader_path`` (see scripts/libraw/build_libraw_openmp.sh
    with ``RAWVIEWER_LIBRAW_OPENMP_STANDALONE=1``). Explicitly pass them to
    PyInstaller so dependency tracing cannot drop the sibling dylibs.
    """
    try:
        import rawpy  # type: ignore
    except Exception:
        return []
    rawpy_dir = Path(rawpy.__file__).resolve().parent
    names = (
        "libraw_r.25.dylib",
        "libomp.dylib",
        "libjpeg.8.dylib",
    )
    return [p for name in names if (p := rawpy_dir / name).is_file()]


def _darwin_real_libintl_candidates(exe_path: Path | None = None) -> list[Path]:
    """Candidate gettext libintl dylibs that export ``_libintl_bindtextdomain``."""
    candidates: list[Path] = []
    # Prefer stable Homebrew cellar paths (avoid `brew --prefix`, which may hit
    # the network JSON API and fail in offline/CI sandboxes).
    for prefix in (
        Path("/opt/homebrew/opt/gettext"),
        Path("/usr/local/opt/gettext"),
    ):
        candidates.append(prefix / "lib" / "libintl.8.dylib")
    brew = shutil.which("brew")
    if brew:
        try:
            prefix = subprocess.check_output(
                [brew, "--prefix", "gettext"],
                text=True,
                stderr=subprocess.DEVNULL,
                timeout=5,
            ).strip()
            if prefix:
                candidates.append(Path(prefix) / "lib" / "libintl.8.dylib")
        except Exception:
            pass
    for env_root in (
        REPO_ROOT / ".pixi" / "envs" / "default",
        Path(sys.prefix),
    ):
        candidates.append(env_root / "lib" / "libintl.8.dylib")
    if exe_path is not None:
        # Prefer OpenCV's full gettext over lensfunpy's stub inside the bundle.
        for hit in sorted(exe_path.rglob("libintl.8.dylib")):
            if "lensfunpy" in hit.parts:
                continue
            if hit.parent.name in ("Frameworks", "Resources") and hit.name == "libintl.8.dylib":
                continue
            if "pyexiv2" in hit.parts:
                continue
            candidates.append(hit)
    return candidates


def _nm_exports(path: Path, symbol: str) -> bool:
    if path.is_symlink():
        try:
            path = path.resolve(strict=True)
        except Exception:
            return False
    if not path.is_file():
        return False
    try:
        out = subprocess.check_output(
            ["nm", "-gU", str(path)],
            text=True,
            stderr=subprocess.DEVNULL,
        )
    except Exception:
        return False
    # Exact symbol match only — substring would confuse
    # ``_g_libintl_bindtextdomain`` with ``_libintl_bindtextdomain``.
    for line in out.splitlines():
        parts = line.split()
        if parts and parts[-1] == symbol:
            return True
    return False


def _libintl_exports_bindtextdomain(path: Path) -> bool:
    return _nm_exports(path, "_libintl_bindtextdomain")


def _libintl_exports_g_libintl(path: Path) -> bool:
    return _nm_exports(path, "_g_libintl_bind_textdomain_codeset")


def _codesign_adhoc(path: Path) -> None:
    subprocess.run(
        ["codesign", "-f", "-s", "-", str(path)],
        check=False,
        capture_output=True,
    )


def _dylib_undefined_symbols(path: Path) -> set[str]:
    try:
        out = subprocess.check_output(
            ["nm", "-u", str(path)],
            text=True,
            stderr=subprocess.DEVNULL,
        )
    except Exception:
        return set()
    return {line.strip() for line in out.splitlines() if line.strip()}


def _dylib_links_libintl(path: Path) -> bool:
    try:
        out = subprocess.check_output(["otool", "-L", str(path)], text=True)
    except Exception:
        return False
    return "libintl" in out


def _rewrite_libintl_dep(dylib: Path, new_dep: str) -> None:
    """Point every libintl dependency on *dylib* at *new_dep*."""
    try:
        deps = subprocess.check_output(["otool", "-L", str(dylib)], text=True)
    except Exception:
        return
    changed = False
    for line in deps.splitlines()[1:]:
        dep = line.strip().split(" ", 1)[0]
        if "libintl" not in Path(dep).name:
            continue
        if dep == new_dep:
            continue
        subprocess.run(
            ["install_name_tool", "-change", dep, new_dep, str(dylib)],
            check=False,
            capture_output=True,
        )
        changed = True
    if changed:
        _codesign_adhoc(dylib)


def _ensure_macos_pyexiv2_libintl_in_app(exe_path: Path) -> None:
    """Split gettext vs lensfunpy proxy libintl so cv2, lensfun, and pyexiv2 all load.

    Three consumers share the name ``libintl.8.dylib`` but need different ABIs:

    * **Real gettext** (``_libintl_*``): OpenCV ``libgnutls`` / ``libglib``, pyexiv2
    * **lensfunpy proxy** (``_g_libintl_*``): lensfunpy ``libglib`` (+ Frameworks copy)

    Putting either one alone at ``Contents/Frameworks/libintl.8.dylib`` breaks the
    other (Lite: missing ``_g_libintl_*``; Full: missing ``_libintl_bindtextdomain``
    → export / AI denoise UI fails because ``import cv2`` fails).

    Fix:
    1. Install **real gettext** at Frameworks/Resources ``libintl.8.dylib`` (cv2 default).
    2. Rewrite every dylib that undefined-refs ``_g_libintl_*`` to load the proxy
       beside lensfunpy (``@loader_path/...`` or an explicit path under lensfunpy).
    3. Keep a gettext copy beside ``pyexiv2/lib/libexiv2.dylib`` with ``@loader_path``.
    """
    if platform.system() != "Darwin":
        return

    stub_src: Path | None = None
    for hit in exe_path.rglob("libintl.8.dylib"):
        if "lensfunpy" in hit.parts and _libintl_exports_g_libintl(hit):
            stub_src = hit.resolve() if hit.is_symlink() else hit
            break
    if stub_src is None:
        raise RuntimeError(
            "lensfunpy proxy libintl.8.dylib not found in app bundle "
            "(needed by lensfunpy libglib)."
        )

    gettext_src: Path | None = None
    for cand in _darwin_real_libintl_candidates(exe_path):
        if _libintl_exports_bindtextdomain(cand):
            gettext_src = cand.resolve() if cand.is_symlink() else cand
            break
    if gettext_src is None:
        raise RuntimeError(
            "Could not find a real gettext libintl.8.dylib for cv2/pyexiv2. "
            "Install with: brew install gettext"
        )

    # 1) Top-level @rpath slot = real gettext (OpenCV libgnutls / cv2 glib).
    for dest in (
        exe_path / "Contents" / "Frameworks" / "libintl.8.dylib",
        exe_path / "Contents" / "Resources" / "libintl.8.dylib",
    ):
        dest.parent.mkdir(parents=True, exist_ok=True)
        if dest.exists() or dest.is_symlink():
            if (
                not dest.is_symlink()
                and _libintl_exports_bindtextdomain(dest)
                and not _libintl_exports_g_libintl(dest)
            ):
                pass  # already correct gettext
            else:
                dest.unlink()
                shutil.copy2(gettext_src, dest)
        else:
            shutil.copy2(gettext_src, dest)
        subprocess.run(
            ["install_name_tool", "-id", "@rpath/libintl.8.dylib", str(dest)],
            check=False,
            capture_output=True,
        )
        _codesign_adhoc(dest)
        if not _libintl_exports_bindtextdomain(dest):
            raise RuntimeError(f"Frameworks libintl missing gettext symbols: {dest}")
        print(f"[OK] Frameworks/Resources libintl is real gettext: {dest}")

    # 2) Point g_libintl consumers at the lensfunpy proxy, not Frameworks gettext.
    stub_rel_from_frameworks = Path("lensfunpy") / "__dot__dylibs" / "libintl.8.dylib"
    # Prefer the real on-disk stub path under the app (handles .dylibs vs __dot__dylibs).
    stub_in_app = stub_src
    try:
        stub_rel_from_frameworks = stub_in_app.relative_to(
            exe_path / "Contents" / "Frameworks"
        )
    except ValueError:
        pass

    g_consumers = 0
    for dylib in exe_path.rglob("*"):
        if not dylib.is_file() or dylib.is_symlink():
            continue
        if dylib.suffix not in (".dylib", ".so"):
            continue
        if "libintl" in dylib.name:
            continue
        if not _dylib_links_libintl(dylib):
            continue
        undef = _dylib_undefined_symbols(dylib)
        if not any(s.startswith("_g_libintl_") for s in undef):
            continue
        # Same directory as a proxy copy → @loader_path; else path from Frameworks.
        local_stub = dylib.parent / "libintl.8.dylib"
        if local_stub.is_file() and _libintl_exports_g_libintl(local_stub):
            new_dep = "@loader_path/libintl.8.dylib"
        else:
            # Frameworks/libglib-2.0.0.dylib etc.
            new_dep = f"@loader_path/{stub_rel_from_frameworks.as_posix()}"
            # If this dylib lives outside Frameworks (e.g. Resources), use absolute
            # @rpath-style path via rewriting to the stub's directory with loader
            # relative path when possible.
            try:
                rel = stub_in_app.relative_to(dylib.parent)
                new_dep = f"@loader_path/{rel.as_posix()}"
            except ValueError:
                try:
                    rel = stub_in_app.relative_to(exe_path / "Contents" / "Frameworks")
                    # Only valid when dylib itself is under Frameworks.
                    dylib.relative_to(exe_path / "Contents" / "Frameworks")
                    new_dep = f"@loader_path/{rel.as_posix()}"
                except ValueError:
                    new_dep = str(stub_in_app)
        _rewrite_libintl_dep(dylib, new_dep)
        g_consumers += 1
        print(f"[OK] g_libintl consumer → {new_dep}: {dylib.relative_to(exe_path)}")
    if g_consumers == 0:
        print("[WARNING] No g_libintl consumers found to rewrite (unexpected).")

    # 3) pyexiv2 keeps a private gettext copy (stable even if Frameworks changes).
    libexiv2_hits = [
        p
        for p in exe_path.rglob("libexiv2.dylib")
        if "pyexiv2" in p.parts and p.is_file() and not p.is_symlink()
    ]
    for libexiv2 in libexiv2_hits:
        local_intl = libexiv2.parent / "libintl.8.dylib"
        if local_intl.exists() or local_intl.is_symlink():
            local_intl.unlink()
        shutil.copy2(gettext_src, local_intl)
        subprocess.run(
            ["install_name_tool", "-id", "@loader_path/libintl.8.dylib", str(local_intl)],
            check=False,
            capture_output=True,
        )
        _codesign_adhoc(local_intl)
        _rewrite_libintl_dep(libexiv2, "@loader_path/libintl.8.dylib")
        if not _libintl_exports_bindtextdomain(local_intl):
            raise RuntimeError(f"pyexiv2 local libintl missing gettext symbols: {local_intl}")
        print(f"[OK] pyexiv2 local gettext beside {libexiv2.relative_to(exe_path)}")


def _ensure_macos_openmp_libraw_in_app(exe_path: Path) -> None:
    """Fail the build if packaged LibRaw is still single-threaded or torch-linked."""
    if platform.system() != "Darwin":
        return
    libraw_hits = list(exe_path.rglob("libraw_r*.dylib"))
    if not libraw_hits:
        print("[WARNING] No libraw dylib in app bundle — OpenMP check skipped.")
        return
    libraw = libraw_hits[0]
    try:
        deps = subprocess.check_output(["otool", "-L", str(libraw)], text=True)
    except Exception as exc:
        print(f"[WARNING] otool failed on {libraw}: {exc}")
        return
    print(f"[INFO] Packaged LibRaw: {libraw}")
    for line in deps.splitlines():
        print(f"  {line}")
    if "torch/lib/libomp" in deps:
        raise RuntimeError(
            "Packaged LibRaw references torch/lib/libomp, but macOS builds "
            "exclude torch. Rebuild with RAWVIEWER_LIBRAW_OPENMP_STANDALONE=1 "
            "(build_macos.sh does this automatically)."
        )
    if "libomp.dylib" not in deps:
        raise RuntimeError(
            "Packaged LibRaw does not link libomp — OpenMP decode inactive. "
            "Run scripts/libraw/build_libraw_openmp.sh before packaging."
        )
    libomp_hits = list(exe_path.rglob("libomp.dylib"))
    if not libomp_hits:
        # Last-chance copy from the build env next to LibRaw.
        for src in _macos_rawpy_openmp_binaries():
            if src.name == "libomp.dylib":
                dest = libraw.parent / "libomp.dylib"
                shutil.copy2(src, dest)
                print(f"[INFO] Copied standalone libomp into bundle: {dest}")
                libomp_hits = [dest]
                break
    if not libomp_hits:
        raise RuntimeError(f"libomp.dylib missing from {exe_path}")
    print(f"[OK] OpenMP LibRaw packaged ({libomp_hits[0]})")


def _prune_built_app(exe_path: Path, profile: str) -> None:
    if platform.system() != 'Darwin':
        return
    print(f"[INFO] Starting post-build pruning for: {exe_path}")
    
    # 1. Prune pycountry locales (saves ~20.0 MB)
    locales_dir = exe_path / "Contents" / "Resources" / "pycountry" / "locales"
    if locales_dir.exists():
        print(f"  Pruning pycountry locales from: {locales_dir}")
        shutil.rmtree(locales_dir, ignore_errors=True)
        
    # 2. Prune unused Qt6 native frameworks (saves ~7.0 MB)
    qt_lib_dir = exe_path / "Contents" / "Frameworks" / "PyQt6" / "Qt6" / "lib"
    if qt_lib_dir.exists():
        unused_frameworks = [
            "QtPdf.framework",
            "QtPdfWidgets.framework",
            "Qt3DAnimation.framework",
            "Qt3DCore.framework",
            "Qt3DExtras.framework",
            "Qt3DInput.framework",
            "Qt3DLogic.framework",
            "Qt3DRender.framework",
            "QtBluetooth.framework",
            "QtCharts.framework",
            "QtDataVisualization.framework",
            "QtDesigner.framework",
            "QtHelp.framework",
            "QtMultimedia.framework",
            "QtMultimediaWidgets.framework",
            "QtNfc.framework",
            "QtPositioning.framework",
            "QtQml.framework",
            "QtQuick.framework",
            "QtQuick3D.framework",
            "QtQuickWidgets.framework",
            "QtRemoteObjects.framework",
            "QtSensors.framework",
            "QtSerialBus.framework",
            "QtSerialPort.framework",
            "QtSpatialAudio.framework",
            "QtSql.framework",
            "QtTest.framework",
            "QtTextToSpeech.framework",
            "QtWebChannel.framework",
            "QtWebEngineCore.framework",
            "QtWebEngineWidgets.framework",
            "QtWebSockets.framework",
            "QtXml.framework",
            "QtSvg.framework",
            "QtNetwork.framework",
        ]
        for fw in unused_frameworks:
            fw_path = qt_lib_dir / fw
            if fw_path.exists():
                print(f"  Pruning unused Qt6 framework: {fw_path}")
                shutil.rmtree(fw_path, ignore_errors=True)

    # 3. Prune Qt6 translations (saves ~6.6 MB; app has no QTranslator)
    qt_translations_dir = (
        exe_path / "Contents" / "Resources" / "PyQt6" / "Qt6" / "translations"
    )
    if qt_translations_dir.exists():
        print(f"  Pruning Qt6 translations from: {qt_translations_dir}")
        shutil.rmtree(qt_translations_dir, ignore_errors=True)

    # 4. Prune tcl/tk runtime if a hook slipped it past the tkinter excludes
    #    (~12 MB: only reachable via PIL.ImageTk, which the app never imports),
    #    and package dist-info metadata dirs (never read at runtime).
    for rel in ("Resources/_tcl_data", "Resources/_tk_data", "Resources/tcl8"):
        leftover = exe_path / "Contents" / rel
        if leftover.exists():
            print(f"  Pruning tcl/tk leftover: {leftover}")
            shutil.rmtree(leftover, ignore_errors=True)
    for area in ("Resources", "Frameworks"):
        base = exe_path / "Contents" / area
        if not base.exists():
            continue
        for lib in base.glob("libt[ck]l*.dylib"):
            print(f"  Pruning tcl/tk dylib: {lib}")
            lib.unlink(missing_ok=True)
        for info in base.glob("*.dist-info"):
            print(f"  Pruning dist-info: {info}")
            shutil.rmtree(info, ignore_errors=True)


def main():
    parser = argparse.ArgumentParser(description="Build RAWviewer executable")
    parser.add_argument(
        "--windows-accel",
        choices=["cuda", "directml"],
        default=os.environ.get("RAWVIEWER_WINDOWS_ACCEL", "cuda").strip().lower() or "cuda",
        help="Windows ONNX acceleration backend (default: cuda). Ignored for --profile lite.",
    )
    parser.add_argument(
        "--profile",
        choices=["full", "plus", "lite", "standard"],
        default=os.environ.get("RAWVIEWER_BUILD_PROFILE", "full").strip().lower() or "full",
        help="Edition: full/plus (AI search) or lite/standard (browse & Adjust). Default: full/plus.",
    )
    parser.add_argument(
        "--keep-dist",
        action="store_true",
        help="Windows: keep other dist/*.exe outputs (build both CUDA and DirectML in one session).",
    )
    parser.add_argument(
        "--sync-version",
        action="store_true",
        help="Write app_version.py and sync pixi.toml from VERSION; exit without building.",
    )
    parser.add_argument(
        "--skip-deps",
        action="store_true",
        help="Skip pip install/upgrade (fast rebuild when the env is already ready).",
    )
    parser.add_argument(
        "--incremental",
        action="store_true",
        help="Keep PyInstaller build/ cache for faster rebuilds.",
    )
    args = parser.parse_args()
    if args.profile in ("standard", "std"):
        args.profile = "lite"
    elif args.profile == "plus":
        args.profile = "full"
    if args.profile not in ("full", "lite"):
        args.profile = "full"

    if args.sync_version:
        sync_version_artifacts()
        print(f"[SUCCESS] Version artifacts synced to {VERSION}")
        sys.exit(0)

    if args.skip_deps:
        os.environ["RAWVIEWER_BUILD_SKIP_DEPS"] = "1"
    if args.incremental:
        os.environ["RAWVIEWER_BUILD_INCREMENTAL"] = "1"

    ensure_project_venv_and_reexec()

    sync_version_artifacts()
    write_build_profile(args.profile)
    is_lite = args.profile == "lite"

    system_name = platform.system()
    if is_lite and system_name == "Windows":
        print("[INFO] Windows lite: no semantic/face AI; EXIF+GPS gallery search only.")
    elif is_lite and system_name == "Darwin":
        print("[INFO] macOS lite: semantic/face AI off; EXIF+GPS metadata search only.")
    if system_name == 'Windows':
        print("RAWviewer Windows Build Script")
        print(f"[INFO] Windows acceleration backend: {args.windows_accel}")
    elif system_name == 'Darwin':
        print(f"RAWviewer macOS Build Script v{VERSION}")
    else:
        print(f"RAWviewer Build Script v{VERSION} ({system_name})")
    print("==============================")
    print("")

    # Install dependencies first
    if not install_dependencies(windows_accel=args.windows_accel, profile=args.profile):
        print("[ERROR] Dependency installation failed.")
        sys.exit(1)

    if platform.system() == "Darwin":
        _darwin_ensure_homebrew_pyexiv2_libs()
        _darwin_preflight_pyexiv2_import()

    print("")
    print("Building RAWviewer executable...")

    # Import PyQt6 after installation
    try:
        import PyQt6
    except ImportError:
        print("[ERROR] PyQt6 not available after installation")
        sys.exit(1)

    # Clean previous builds (skip build/ wipe for incremental PyInstaller runs).
    incremental = _build_incremental()
    if incremental:
        _build_log("Incremental build: keeping PyInstaller cache in build/")
    print("Cleaning previous builds...")
    windows_target_setup = (
        "RAWviewer_Setup"
        if platform.system() == "Windows"
        else None
    )
    
    # Try to kill any running RAWviewer.exe processes on Windows
    if platform.system() == 'Windows':
        for image in (
            "RAWviewer.exe",
            "RAWviewer_Setup.exe",
            "RAWviewer_Setup_CUDA.exe",
            "RAWviewer_Setup_DirectML.exe",
            "RAWviewer_Setup_Lite.exe",
        ):
            try:
                result = subprocess.run(
                    ['taskkill', '/F', '/IM', image, '/T'],
                    capture_output=True,
                    text=True,
                )
                if result.returncode == 0:
                    print(f"Closed running {image} instances")
            except Exception as e:
                print(f"[WARNING] Could not close running {image} instances: {e}")
        time.sleep(1)
    
    # Clean build directory
    if os.path.exists('build') and not incremental:
        try:
            print("Cleaning build directory...")
            shutil.rmtree('build')
        except PermissionError as e:
            print(f"[WARNING] Could not delete build directory: {e}")
            print("  Continuing anyway...")
        except Exception as e:
            print(f"[WARNING] Error cleaning build directory: {e}")
    elif os.path.exists('build') and incremental:
        _build_log("Reusing existing build/ directory")
    
    # Clean dist directory (try to delete specific files first)
    if os.path.exists('dist'):
        try:
            if args.keep_dist and platform.system() == "Windows" and windows_target_setup:
                target_file = os.path.join("dist", f"{windows_target_setup}.exe")
                if os.path.exists(target_file):
                    print(f"Cleaning dist directory (keeping other installers)...")
                    try:
                        os.remove(target_file)
                        print(f"  Removed {windows_target_setup}.exe")
                    except PermissionError:
                        print(f"[ERROR] Cannot delete {windows_target_setup}.exe - it may be running.")
                        print("  Please close RAWviewer and try again.")
                        sys.exit(1)
                    except Exception as e:
                        print(f"[WARNING] Could not delete {windows_target_setup}.exe: {e}")
            else:
                print("Cleaning dist directory...")
                if platform.system() == "Windows":
                    for name in (
                        "RAWviewer.exe",
                        "RAWviewer_Setup.exe",
                        "RAWviewer_Setup_CUDA.exe",
                        "RAWviewer_Setup_DirectML.exe",
                        "RAWviewer_Setup_Lite.exe",
                    ):
                        candidate = os.path.join("dist", name)
                        if os.path.exists(candidate):
                            try:
                                os.remove(candidate)
                                print(f"  Removed {name}")
                            except PermissionError:
                                print(f"[ERROR] Cannot delete {name} - it may be running.")
                                print("  Please close RAWviewer and try again.")
                                sys.exit(1)
                            except Exception as e:
                                print(f"[WARNING] Could not delete {name}: {e}")
                elif platform.system() == "Darwin":
                    target_bundle = _macos_app_bundle_name(args.profile) + ".app"
                    bundles = [target_bundle] if incremental else ("RAWviewer.app", "RAWviewer_Lite.app")
                    for bundle in bundles:
                        candidate = os.path.join("dist", bundle)
                        if os.path.exists(candidate):
                            try:
                                shutil.rmtree(candidate)
                                print(f"  Removed {bundle}")
                            except PermissionError:
                                print(f"[ERROR] Cannot delete {bundle} - it may be running.")
                                print("  Please close RAWviewer and try again.")
                                sys.exit(1)
                            except Exception as e:
                                print(f"[WARNING] Could not delete {bundle}: {e}")
                else:
                    exe_name = "RAWviewer"
                    exe_path = os.path.join("dist", exe_name)
                    if os.path.exists(exe_path):
                        try:
                            os.remove(exe_path)
                            print(f"  Removed {exe_name}")
                        except PermissionError:
                            print(f"[ERROR] Cannot delete {exe_name} - it may be running.")
                            print("  Please close RAWviewer and try again.")
                            sys.exit(1)
                        except Exception as e:
                            print(f"[WARNING] Could not delete {exe_name}: {e}")

                # Full clean only — incremental keeps release zips / other dist artifacts.
                if not incremental:
                    try:
                        shutil.rmtree('dist')
                    except PermissionError:
                        print("[WARNING] Some files in dist directory are locked, but continuing...")
                    except Exception as e:
                        print(f"[WARNING] Could not fully clean dist directory: {e}")
                else:
                    _build_log("Keeping other dist/ outputs (incremental)")
        except Exception as e:
            print(f"[WARNING] Error cleaning dist directory: {e}")

    # Prevent stale local logs from being packed into installer payload ("src;src").
    logs_dir = Path("src") / "logs"
    if logs_dir.exists():
        try:
            print("Cleaning src/logs before packaging...")
            shutil.rmtree(logs_dir)
        except Exception as e:
            print(f"[WARNING] Could not clean src/logs: {e}")
    # Platform-agnostic icon
    if platform.system() == 'Windows':
        icon_file = os.path.join('icons', 'appicon.ico')
    elif platform.system() == 'Darwin':
        icon_file = os.path.join('icons', 'appicon.icns')
    else:
        icon_file = os.path.join('icons', 'appicon.ico')  # fallback
    icon_path = os.path.abspath(icon_file)
    if not os.path.exists(icon_path):
        print(f"[ERROR] Icon file not found: {icon_path}")
        if platform.system() == "Windows":
            sys.exit(1)
        icon_arg = ''
    else:
        icon_arg = f'--icon "{icon_path}"'
    # Find PyQt6 imageformats plugin path
    pyqt_path = os.path.dirname(PyQt6.__file__)
    if platform.system() == 'Windows':
        imageformats_src = os.path.join(
            pyqt_path, 'Qt6', 'plugins', 'imageformats')
        add_data_sep = ';'
    elif platform.system() == 'Darwin':
        imageformats_src = os.path.join(
            pyqt_path, 'Qt6', 'plugins', 'imageformats')
        add_data_sep = ':'
    else:
        imageformats_src = os.path.join(
            pyqt_path, 'Qt6', 'plugins', 'imageformats')
        add_data_sep = ':'
    # Selectively copy icons and database files to avoid platform duplicates
    if platform.system() == 'Windows':
        add_data_args = [
            f'--add-data "{imageformats_src}{add_data_sep}imageformats"',
            f'--add-data "icons{os.sep}appicon.ico{add_data_sep}icons"',
            f'--add-data "icons{os.sep}appicon.png{add_data_sep}icons"',
            f'--add-data "src{os.sep}icons{os.sep}folder_open_md3.svg{add_data_sep}icons"',
            f'--add-data "src{os.sep}icons{os.sep}cities500.csv.gz{add_data_sep}icons"',
            f'--add-data "src{os.sep}icons{os.sep}landmarks.csv.gz{add_data_sep}icons"',
        ]
    else:
        add_data_args = [
            f'--add-data "{imageformats_src}{add_data_sep}imageformats"',
            f'--add-data "icons{os.sep}appicon.icns{add_data_sep}icons"',
            f'--add-data "icons{os.sep}appicon.png{add_data_sep}icons"',
            f'--add-data "src{os.sep}icons{os.sep}folder_open_md3.svg{add_data_sep}icons"',
            f'--add-data "src{os.sep}icons{os.sep}cities500.csv.gz{add_data_sep}icons"',
            f'--add-data "src{os.sep}icons{os.sep}landmarks.csv.gz{add_data_sep}icons"',
        ]
    app_bundle_name = _macos_app_bundle_name(args.profile)
    windows_pixi_manifest = None
    if platform.system() == "Darwin":
        print(f"[INFO] macOS app bundle: dist/{app_bundle_name}.app")
        if is_lite:
            print("[INFO] macOS lite release: no MobileCLIP / face AI; EXIF+GPS gallery search only.")
        else:
            print("[INFO] macOS release: MobileCLIP Core ML models are NOT bundled; users download in-app on first use.")
    elif platform.system() == "Windows":
        add_data_args.append('--add-data "uninstall.bat;."')
        add_data_args.append('--add-data "scripts;scripts"')
        
        # Prepare installer pixi.toml variants (CUDA+CuPy, DirectML, Lite).
        cuda_manifest = _prepare_windows_pixi_manifest("cuda", profile="full")
        dml_manifest = _prepare_windows_pixi_manifest("directml", profile="full")
        lite_manifest = _prepare_windows_pixi_manifest("directml", profile="lite")
        
        cuda_str = str(cuda_manifest).replace("\\", "/")
        dml_str = str(dml_manifest).replace("\\", "/")
        lite_str = str(lite_manifest).replace("\\", "/")
        
        add_data_args.append(f'--add-data "{cuda_str};."')
        add_data_args.append(f'--add-data "{dml_str};."')
        add_data_args.append(f'--add-data "{lite_str};."')
        
        app_bundle_name = "RAWviewer_Setup"
        launcher_exe, launcher_runtime = build_windows_launcher_stub(
            icon_path if os.path.exists(icon_path) else None
        )
        add_data_args.append(f'--add-data "{launcher_exe.resolve()};."')
        add_data_args.append(f'--add-data "{launcher_runtime.resolve()};_launcher"')
        print(f"[INFO] Windows installer output: dist\\{app_bundle_name}.exe")
        print("[INFO] Bundling Windows manifests (CUDA+CuPy, DirectML, Lite).")
    add_data_arg_str = " ".join(add_data_args)

    src_path = os.path.abspath('src')
    
    cmd_base = [
        sys.executable, "-m", "PyInstaller",
        "--noconfirm",
        "--windowed",
        "--paths", src_path,
        "--hidden-import", "rawviewer_ui.gallery_view",
        "--hidden-import", "rawviewer_ui.widgets",
        "--hidden-import", "rawviewer_ui.mobileclip_download_dialog",
        "--hidden-import", "natsort",
        "--hidden-import", "send2trash",
        "--hidden-import", "metadata_backend",
        "--hidden-import", "fast_raw_decode",
        "--hidden-import", "rawviewer_profile",
        "--hidden-import", "build_profile",
        "--hidden-import", "app_version",
        "--name", app_bundle_name
    ]
    try:
        import pyexiv2  # noqa: F401

        if platform.system() in ("Darwin", "Windows"):
            cmd_base.extend(["--hidden-import", "pyexiv2", "--collect-all", "pyexiv2"])
            print("[INFO] PyInstaller: bundling pyexiv2 with --collect-all (native Exiv2 libs).")
    except ImportError:
        print(
            "[WARNING] pyexiv2 not importable; build continues without pyexiv2 bundling. "
            "Install pyexiv2 before packaging for EXIF read/write in the app."
        )

    if platform.system() == "Darwin":
        cmd_base.extend([
            "--hidden-import", "objc",
            "--hidden-import", "AppKit",
            "--hidden-import", "Foundation",
            "--hidden-import", "Quartz",
            "--hidden-import", "certifi",
            "--hidden-import", "ssl_certs",
            "--collect-data", "certifi",
            # PyInstaller 6.21 appends "__main__" to a *mutable* excludes list
            # inside initialize_modgraph, so the cached Analysis guts never match
            # the next run's input and every incremental build re-runs Analysis
            # ("Building because excludes changed"). Listing it ourselves skips
            # that append and keeps the Analysis cache valid.
            "--exclude-module", "__main__",
            "--exclude-module", "coremltools",
            "--exclude-module", "torch",
            "--exclude-module", "torchvision",
            # GPU demosaic (gpu_raw_processor) is default-off on macOS
            # (RAWVIEWER_PREFER_GPU_DECODE=0); kornia exists only for it, and
            # its static import would otherwise drag the package in.
            "--exclude-module", "kornia",
            "--exclude-module", "kornia_rs",
            "--exclude-module", "sentence_transformers",
            "--exclude-module", "transformers",
            "--exclude-module", "sklearn",
            "--exclude-module", "tokenizers",
            "--exclude-module", "safetensors",
            # cv2 was excluded here (true at the time -- "unused native
            # extensions & optional/future packages") but the scene-linear
            # Adjust panel added since imports cv2 unconditionally
            # (raw_edit_pipeline.py, raw_chroma_denoise.py,
            # raw_detail_enhance.py, raw_hsl.py, raw_lens_correction.py) --
            # excluding it here made every macOS build (Full and Lite) crash
            # with ModuleNotFoundError the moment any Adjust panel control
            # ran. Must stay bundled. See docs/EDIT_PIPELINE.md "Installer size".
            "--exclude-module", "pyqtgraph",
            "--exclude-module", "hf_xet",
            # tkinter is only reachable via PIL.ImageTk (unused) but drags
            # libtcl/libtk + _tcl_data/tcl8 (~12MB) into the bundle.
            "--exclude-module", "tkinter",
            "--exclude-module", "_tkinter",
            "--exclude-module", "setuptools",
            "--exclude-module", "PyObjCTest",
        ])
        # OpenMP LibRaw siblings (standalone libomp + libjpeg). build_macos.sh
        # installs these via scripts/libraw/build_libraw_openmp.sh before packaging.
        for bin_path in _macos_rawpy_openmp_binaries():
            cmd_base.extend(["--add-binary", f"{bin_path}:rawpy"])
            print(f"[INFO] Bundling OpenMP LibRaw binary: {bin_path.name}")
        
        # Exclude unused heavy PyQt6 modules to keep built bundle lightweight
        unused_pyqt6 = [
            "PyQt6.Qt3DAnimation", "PyQt6.Qt3DCore", "PyQt6.Qt3DExtras", "PyQt6.Qt3DInput",
            "PyQt6.Qt3DLogic", "PyQt6.Qt3DRender", "PyQt6.QtBluetooth", "PyQt6.QtCharts",
            "PyQt6.QtDataVisualization", "PyQt6.QtDesigner", "PyQt6.QtHelp", "PyQt6.QtMultimedia",
            "PyQt6.QtMultimediaWidgets", "PyQt6.QtNetwork", "PyQt6.QtNfc", "PyQt6.QtPdf",
            "PyQt6.QtPdfWidgets", "PyQt6.QtPositioning", "PyQt6.QtQml", "PyQt6.QtQuick",
            "PyQt6.QtQuick3D", "PyQt6.QtQuickWidgets", "PyQt6.QtRemoteObjects", "PyQt6.QtSensors",
            "PyQt6.QtSerialBus", "PyQt6.QtSerialPort", "PyQt6.QtSpatialAudio", "PyQt6.QtSql",
            "PyQt6.QtTest", "PyQt6.QtTextToSpeech", "PyQt6.QtWebChannel", "PyQt6.QtWebEngineCore",
            "PyQt6.QtWebEngineWidgets", "PyQt6.QtWebSockets", "PyQt6.QtXml", "PyQt6.QtSvg",
            "PyQt6.QtSvgWidgets"
        ]
        for mod in unused_pyqt6:
            cmd_base.extend(["--exclude-module", mod])

        if is_lite:
            cmd_base.extend([
                "--exclude-module", "huggingface_hub",
                "--exclude-module", "httpx",
                "--exclude-module", "CoreML",
                "--exclude-module", "Vision",
            ])
        else:
            cmd_base.extend([
                "--hidden-import", "requests",
                "--hidden-import", "CoreML",
                "--hidden-import", "Vision",
                "--hidden-import", "huggingface_hub",
            ])
    elif platform.system() == "Windows":
        cmd_base.extend([
            "--hidden-import", "win32com.client",
            "--hidden-import", "pythoncom",
            "--hidden-import", "pywintypes",
        ])
        # Exclude unused heavy PyQt6 modules to keep built bootstrapper lightweight
        unused_pyqt6 = [
            "PyQt6.Qt3DAnimation", "PyQt6.Qt3DCore", "PyQt6.Qt3DExtras", "PyQt6.Qt3DInput",
            "PyQt6.Qt3DLogic", "PyQt6.Qt3DRender", "PyQt6.QtBluetooth", "PyQt6.QtCharts",
            "PyQt6.QtDataVisualization", "PyQt6.QtDesigner", "PyQt6.QtHelp", "PyQt6.QtMultimedia",
            "PyQt6.QtMultimediaWidgets", "PyQt6.QtNetwork", "PyQt6.QtNfc", "PyQt6.QtPdf",
            "PyQt6.QtPdfWidgets", "PyQt6.QtPositioning", "PyQt6.QtQml", "PyQt6.QtQuick",
            "PyQt6.QtQuick3D", "PyQt6.QtQuickWidgets", "PyQt6.QtRemoteObjects", "PyQt6.QtSensors",
            "PyQt6.QtSerialBus", "PyQt6.QtSerialPort", "PyQt6.QtSpatialAudio", "PyQt6.QtSql",
            "PyQt6.QtTest", "PyQt6.QtTextToSpeech", "PyQt6.QtWebChannel", "PyQt6.QtWebEngineCore",
            "PyQt6.QtWebEngineWidgets", "PyQt6.QtWebSockets", "PyQt6.QtXml", "PyQt6.QtSvg",
            "PyQt6.QtSvgWidgets"
        ]
        for mod in unused_pyqt6:
            cmd_base.extend(["--exclude-module", mod])

        # Windows uses Pixi bootstrap. Exclude everything except PyQt6 and standard libs
        cmd_base.extend([
            "--exclude-module", "torch",
            "--exclude-module", "torchvision",
            "--exclude-module", "tensorboard",
            "--exclude-module", "sentence_transformers",
            "--exclude-module", "transformers",
            "--exclude-module", "scipy",
            "--exclude-module", "matplotlib",
            "--exclude-module", "onnxruntime",
            "--exclude-module", "rawpy",
            "--exclude-module", "numpy",
            "--exclude-module", "PIL",
            "--exclude-module", "pyexiv2",
            "--exclude-module", "pyqtgraph",
            "--exclude-module", "natsort",
            "--exclude-module", "send2trash",
            "--exclude-module", "exifread",
            "--exclude-module", "hf_xet",
            "--exclude-module", "tkinter",
            "--exclude-module", "_tkinter",
            "--exclude-module", "setuptools",
            # Torch-free era heavies: the bootstrapper's hidden-imports of the
            # UI modules otherwise sweep these into the setup exe (~1.2 GB vs
            # ~100 MB). The installed app gets them via pixi at install time.
            "--exclude-module", "cupy",
            "--exclude-module", "cupy_backends",
            "--exclude-module", "cupyx",
            "--exclude-module", "fastrlock",
            "--exclude-module", "cv2",
            "--exclude-module", "kornia",
            "--exclude-module", "kornia_rs",
            "--exclude-module", "sympy",
            "--exclude-module", "mpmath",
            "--exclude-module", "networkx",
            "--exclude-module", "lensfunpy",
            "--exclude-module", "pillow_heif",
            "--exclude-module", "tifffile",
            "--exclude-module", "huggingface_hub",
        ])
        
        add_data_args.append('--add-data "src;src"')
    
    if platform.system() == 'Darwin':
        cmd_base.append("--onedir")
        macos_pool_hook = os.path.join(src_path, "pyi_rth_macos_process_pool.py")
        release_defaults_hook = os.path.join(src_path, "pyi_rth_release_defaults.py")
        ssl_certs_hook = os.path.join(src_path, "pyi_rth_ssl_certs.py")
        profile_hook = os.path.join(src_path, "pyi_rth_profile_defaults.py")
        if os.path.isfile(ssl_certs_hook):
            cmd_base.extend(["--runtime-hook", ssl_certs_hook])
        if os.path.isfile(profile_hook):
            cmd_base.extend(["--runtime-hook", profile_hook])
        if os.path.isfile(macos_pool_hook):
            cmd_base.extend(["--runtime-hook", macos_pool_hook])
        if os.path.isfile(release_defaults_hook):
            cmd_base.extend(["--runtime-hook", release_defaults_hook])
        bundle_id = "com.markyip.rawviewer.lite" if is_lite else "com.markyip.rawviewer"
        cmd_base.extend(["--osx-bundle-identifier", bundle_id])
    else:
        cmd_base.append("--onefile")
        release_defaults_hook = os.path.join(src_path, "pyi_rth_release_defaults.py")
        profile_hook = os.path.join(src_path, "pyi_rth_profile_defaults.py")
        if os.path.isfile(profile_hook):
            cmd_base.extend(["--runtime-hook", profile_hook])
        if os.path.isfile(release_defaults_hook):
            cmd_base.extend(["--runtime-hook", release_defaults_hook])
        
    if icon_arg:
        if platform.system() == 'Windows':
            cmd_base.extend(["--icon", icon_path])
        else:
            cmd_base.extend(["--icon", icon_path])
            
    # Add data
    for arg in add_data_args:
        cmd_base.extend(["--add-data", arg.split('--add-data ')[-1].strip('"')])
        
    if platform.system() == 'Windows':
        cmd_base.append("src/bootstrap.py")
    else:
        cmd_base.append("src/main.py")

    print(f"Running: {' '.join(cmd_base)}")
    _build_log("Starting PyInstaller")
    if not run_command(cmd_base):
        print("[ERROR] Build failed.")
        sys.exit(1)
    _build_log("PyInstaller finished")
    if platform.system() == 'Windows':
        exe_path = Path("dist") / f"{app_bundle_name}.exe"
    elif platform.system() == 'Darwin':
        exe_path = Path("dist") / f"{app_bundle_name}.app"
    else:
        exe_path = Path("dist") / app_bundle_name
    if exe_path.exists():
        print(f"[SUCCESS] Executable created: {exe_path}")
        if platform.system() == 'Darwin':
            print("Patching macOS Info.plist...")
            update_macos_plist(str(exe_path), profile=args.profile)
            _prune_built_app(exe_path, args.profile)
            _ensure_macos_pyexiv2_libintl_in_app(exe_path)
            _ensure_macos_openmp_libraw_in_app(exe_path)
            if _env_flag("RAWVIEWER_BUILD_FAST_SIGN"):
                print("Re-signing macOS app (executable only, fast)...")
                macos_exe = exe_path / "Contents" / "MacOS" / app_bundle_name
                if macos_exe.is_file():
                    run_command(["codesign", "--force", "-s", "-", str(macos_exe)])
                run_command(["codesign", "--force", "-s", "-", str(exe_path)])
            else:
                print("Re-signing macOS app bundle (ad-hoc)...")
                run_command(["codesign", "--force", "--deep", "-s", "-", str(exe_path)])
            print("Clearing macOS quarantine attribute...")
            run_command(['xattr', '-cr', str(exe_path)])
    else:
        print("[ERROR] Executable was not created!")
        
    if platform.system() == 'Windows' and exe_path.exists():
        print("Build completed successfully.")
        print(f"  Installer: {exe_path}")
        print("  (Installs a separate RAWviewer.exe launcher stub into the chosen folder.)")


if __name__ == '__main__':
    try:
        main()
    except Exception as e:
        print(f"[CRITICAL ERROR] Build script crashed: {e}")
        sys.exit(1)
    
    # If main() returns None/0 but we want to check if it really succeeded
    # Actually main() doesn't return anything, so we should check for failures inside main()
